---
title: ''
output: html_document
---

# 📈 **Repeated Measures (q measures)**
## **0.** Settings
```{r, warning=FALSE, message=FALSE}
library(car)
load("mcshapiro.test.RData")
```

## **1.** Data
```{r, warning=FALSE, message=FALSE}
data = read.table ('pressure.txt', col.names=c('h.0','h.8','h.16','h.24'))
```

## **2.** Assumptions and EDA
```{r, warning=FALSE, message=FALSE}
mcshapiro.test(data)
matplot(t(data), type='l')
```

```{r, warning=FALSE, message=FALSE}
# MATPLOT DATA FORMAT
#
#     |--------|--------|----|--------|
#     | meas.1 | meas.2 | .. | meas.q |
# |---|--------|--------|----|--------|
# | 1 |   ..   |   ..   | .. |   ..   | 
# | 2 |   ..   |   ..   | .. |   ..   | 
# |   |   ..   |   ..   | .. |   ..   |
# |---|--------|--------|----|--------|
#
# Rows are independent.
```

```{r, warning=FALSE, message=FALSE}
# Dimensions
n = dim(data)[1]
q = dim(data)[2]

# Mean
M = sapply(data, mean)
M

# Covariance
S = cov(data)
S

# Contrast matrix
C = matrix(c(-1, 1, 0, 0,
             -1, 0, 1, 0,
             -1, 0, 0, 1), 3, 4, byrow=T)
C
```

## **3.** Testing
```{r, warning=FALSE, message=FALSE}
# H0: C%*%mu == 0
# H1: C%*%mu != 0

# Estimates
data.mean   = C %*% M
data.cov    = C %*% S %*% t(C)
data.invcov = solve(data.cov)

# Mean to test
mu0 = seq(0,0, length = q-1)

# Alpha
alpha = 0.05

# Dimensions (pt. 2)
p = q-1
```

## **4.** Work on the mean
```{r, warning=FALSE, message=FALSE}
# From here it is sufficient to use the previous code.
# ('Test and CR for the mean of a multivariate Gaussian - One population')

# INTERPRETATIONS
# Case : 1 measurement (x0) before some drugs, 3 measurements (x1,x2,x3) post drugs
#
# Request 1 : 
#   "Perform a test at level 5% to prove that the drug has influence"
#   NOTE: Just test (CI only if explicitley required).
#   How-to: (1) contrast matrix that compares (x1-x0, x2-x0, x3-x0)
#           (2) contrast matrix that compares (x1-x0, x2-x1, x3-x2)
#
# Request 2 :
#   "Highlight the effect of the drug on the blood pressure"
#   How-to: CI to see if <variable> changes (e.g. pressure)
#
# Request 3 : 
#   "The drug decreases the pressure of two units w.r.t. the baseline at
#    both times x1 and x2, and its effect vanishes at x3"
#   How-to: C = matrix(c(-1, 1, 0, 0,
#                        -1, 0, 1, 0,
#                        -1, 0, 0, 1), 3, 4, byrow=T)
#           mu0 = c(2,2,0)
```